export const CHECK_AUTH = 'CHECK_AUTH'
export const LOGIN_USER = 'LOGIN_USER'
export const REGISTRATION_USER = 'REGISTRATION_USER'
export const CONFIRM_REGISTRATION = 'CONFIRM_REGISTRATION'
export const LOGOUT = 'LOGOUT'

export const POST_PAYMENT = 'POST_PAYMENT'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
